config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/how_it_works'

  root 'welcome#index'

  resources :documentaries
  resource :sessions, only: [:new, :destroy]

end

app/models/documentary.rb
class Documentary < ActiveRecord::Base
  has_many :genres, :through => :documentary_has_genres
  has_many :documentary_has_genres
end

app/models/documentary_has_genre.rb
class DocumentaryHasGenre < ActiveRecord::Base
  belongs_to :documentary
  belongs_to :genre
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :documentaries, :through => :documentary_has_genres
  has_many :documentary_has_genres

  def count_documentaries
    DocumentaryHasGenre.where(:genre_id => self.id).count
  end
end

app/models/user.rb
class User

  attr_accessor :user_id

  def initialize user_id
    @user_id = user_id
  end

  def is_authenticated?
    @user_id != nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/documentaries_controller.rb
class DocumentariesController < ApplicationController
  def index
    params[:status] ||= :new
    params[:type] ||= :new

    @documentaries = Documentary.includes(:genres).where(status: params[:status].to_s)

    @documentaries = case params[:type].to_sym
    when :new
      @documentaries.order(created_at: :desc)
    when :approved
      @documentaries.where(approved: true)
    when :top
      @documentaries.order(backers: :desc)
    when :completed
      @documentaries.where(percent_funded: 100)
    else
      @documentaries.order(created_at: :desc)
    end

    @documentaries = @documentaries.where(genres: {title: params[:genre]}) if params[:genre]
  end

  def new
    @documentary = Documentary.new
  end

  def create
    @documentary = Documentary.create(documentary_params)
    redirect_to documentary_path(@documentary.id)
  end

  def show
    @documentary= Documentary.find(params[:id])
    @avatar= Faker::Avatar.image("random", "40x40")
    @item_image= Faker::Avatar.image("item", "100x100")
  end

  private

  def documentary_params
    params.require(:documentary).permit(:title, :short_synopsis, :long_synopsis, :city, :budget, :purpose,
                                        :thumnail_url,
                                        :pitch_video_url,
                                        :expired_at => [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:user_id] = 1

    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include SessionsHelper

  def index
    @my_documentaries = current_user.is_authenticated? ? Documentary.limit(5) : []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def all_genres
    @all_genres ||= @documentaries.map(&:genres).flatten.uniq
  end

  def is_active? value, default_value
    value.to_sym == default_value ? :active : nil
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.new(session[:user_id])
  end
end

app/views/documentaries/index.html.slim
h1
  | Projects


ul.nav.nav-tabs
  li role="presentation" class="#{ is_active?(params[:type], :new) }"
    = link_to type: :new do
      | New Projects
  li role="presentation" class="#{ is_active?(params[:type], :approved) }"
    = link_to type: :approved, status: params[:status] do
      | ONF/NFB Approved
  li role="presentation" class="#{ is_active?(params[:type], :top) }"
    = link_to type: :top, status: params[:status] do
      | Top likes
  li role="presentation" class="#{ is_active?(params[:type], :completed) }"
    = link_to type: :completed, status: params[:status] do
      | Completed

br

- @documentaries.each do |documentary|
  .panel.panel-default
    .panel-heading
      = documentary.title
    .panel-body
      .row
        .col-xs-2
          .thumbnail
            = link_to(image_tag(documentary.thumbnail_url, :size => "121x110"), documentary_path(documentary.id))
        .col-xs-8
          = documentary.short_synopsis
        .col-xs-2
          p.bg-success.text-center
            = documentary.genres.map(&:title).first.humanize
    .panel-footer
      .row
        .col-xs-4
          .i.fa.fa-user
            = documentary.creator
        .col-xs-6
          .i.fa.fa-heart
            = "%s" % documentary.backers
        .col-xs-2
          .i.fa.fa-clock-o
            = documentary.expired_at.strftime("%B %d, %Y")
      .row
        .col-xs-12
          .progress
            .progress-bar role="progressbar" aria-valuenow=documentary.percent_funded aria-valuemin="0" aria-valuemax="100" style="width: #{documentary.percent_funded}%;"
              = "%s %" % documentary.percent_funded

- content_for :right_panel do
  - if current_page?(documentaries_url) && !all_genres.blank?
    .col-lg-3
      .well.sidebar-nav style="margin-top: 131px;"
        ul.nav.nav-pills.nav-stacked
          - all_genres.each do |genre|
            li class="#{ params[:genre] == genre.title.underscore ? "active" : nil }"
              = link_to genre: genre.title, type: params[:type], status: params[:status] do
                = genre.title.humanize
                span.badge
                  = genre.count_documentaries

app/views/documentaries/new.html.slim
= simple_form_for(@documentary, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  ) do |form|
    = form.error_notification
    = form.input :title, placeholder: 'The title of your documentary'
    = form.input :short_synopsis, as: :text, placeholder: 'A short synopsis of your documentary'
    = form.input :long_synopsis , as: :text, placeholder: 'THE synopsis of your documentary'
    = form.input :expired_at, as: :date
    = form.input :city, placeholder: 'The city of the shooting'
    = form.input :budget, hint: 'This is the place where you put how much monet do you need to bring your project to life'
    = form.input :purpose, as: :text, placeholder: 'The place to write why should the canayan citizen support your project'
    = form.input :thumbnail_url, as: :url, hint: 'The url to the image of your project'
    = form.input :pitch_video_url, as: :url, hint: 'The url to your pitch video (must be in embed format ex)'
    = form.button :submit, :class => "btn btn-primary"

app/views/documentaries/show.html.slim
h1
  = @documentary.title 
  small.pull-right.vote
    | &nbsp;
    a class="fa fa-heart fa-heart-o"
      |  I like this project

.row
  .col-xs-2
    span
      | Created by: 
      a href="#" = @documentary.creator
    br
    br

.row
  .col-xs-2
    = facebook_button
  .col-xs-2
    = twitter_button
  .col-xs-8
    .h3.pull-right
      span.label.label-default = @documentary.city
      span &nbsp;
      span.label.label-primary = @documentary.genres.map(&:title).first.humanize

.page-header
  hr style="color:black" size=30
  .embed-responsive.embed-responsive-16by9
    iframe.embed-responsive-item src="#{@documentary.pitch_video_url}" width="516"
  hr
  h3 Synopsis
  p = @documentary.long_synopsis
  hr
  h3 Budget & Progress
  div = "Final budget %s" % number_to_currency(@documentary.budget)
  .progress
    .progress-bar role="progressbar" aria-valuenow=@documentary.percent_funded aria-valuemin="0" aria-valuemax="100" style="width: #{@documentary.percent_funded}%;"
      = "%s %" % @documentary.percent_funded

div role="tabpanel"
  ul.nav.nav-tabs.js role="tablist"
    li.active role="presentation"
      = link_to "Wishlist", "#wishlist", role: "tab"
    li role="presentation"
      = link_to "Details", "#details", role: "tab"
    li role="presentation"
      = link_to "Blog", "#blog", role: "tab"
    li role="presentation"
      = link_to "Team", "#team", role: "tab"
    li role="presentation"
      = link_to "#backers", role: "tab" do
        | Backers &nbsp;
        span.badge
          = @documentary.backers


  div.tab-content
    div role="tabpanel" class="tab-pane active" id="wishlist"
      h3 Wishlist
      table
        tr
          td
            h4 Storage
        tr.wishlist-item
          td
            img src=@item_image
          td.wishlist-item-info
            div.wishlist-item-name Extra Super Awesome Hard Drive
            div.wishlist-item-description Integer aliquet sollicitudin maximus. In ornare, purus vel ullamcorper bibendum, nunc nisl blandit lacus, ac consequat elit nibh in ante. Donec viverra eros sed arcu placerat tempus.
          td 150$ per unit
          td
            | 1 of 1
            br fulfilled
          td
            select
              option 1
          td
            button.btn.btn-success.disabled Fulfilled

    div role="tabpanel" class="tab-pane" id="details"
      h3 Details
      h4 Location
      p = @documentary.city
      h4 Synopsis
      p Phasellus suscipit rutrum luctus. Mauris iaculis porttitor eros. Maecenas commodo facilisis tellus at convallis. Ut venenatis odio sit amet diam aliquam vulputate. Duis iaculis bibendum libero eu scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut sed lectus mi.
      p Nunc et mauris iaculis, mattis erat eget, dictum elit. Integer id massa convallis urna tempor vestibulum in eu tellus. Fusce eu sem iaculis ipsum egestas imperdiet id et nunc. Etiam bibendum risus quam, a vulputate est tempor nec. In sit amet tristique urna. Vivamus elit augue, dapibus id purus eget, tempor vestibulum ante. Vivamus vulputate dictum purus ac consectetur. Nullam sollicitudin rutrum fringilla. Phasellus maximus metus ut odio vulputate, in mollis tellus commodo. Integer aliquet sollicitudin maximus. In ornare, purus vel ullamcorper bibendum, nunc nisl blandit lacus, ac consequat elit nibh in ante. Donec viverra eros sed arcu placerat tempus.
      p Vestibulum congue vel turpis eget posuere. Proin mattis est ut eros malesuada, eu consequat tortor malesuada. Ut purus metus, consectetur ac vestibulum in, fermentum quis felis. Proin non quam non felis suscipit aliquet. Nulla dapibus urna vel sem feugiat vestibulum.
      h4 Schedule
      p Today + Tomorrow
      h4 Distribution Plan
      p Ut ullamcorper at odio in ullamcorper. Mauris eleifend dictum tristique. Etiam gravida justo vel mauris accumsan, sed condimentum nibh imperdiet. Nullam ac lacinia leo. Pellentesque convallis, arcu non luctus pretium, sapien turpis porta nunc, nec imperdiet arcu nulla iaculis nisl. Nulla laoreet diam ut velit mattis, quis tristique purus hendrerit. Nunc euismod pulvinar vestibulum. Quisque bibendum lectus quis accumsan auctor. In a nulla eu velit malesuada efficitur in ac augue. Morbi semper neque sit amet risus porta, vitae cursus urna sagittis. Aliquam rutrum velit quis ex facilisis pellentesque.
      p Maecenas commodo facilisis tellus at convallis. Ut venenatis odio sit amet diam aliquam vulputate.
      p Quisque eu neque eu nibh efficitur tempor ut id nulla. Sed elementum, mi at porttitor vulputate, arcu metus ultrices lacus, in rhoncus elit orci quis orci. Vestibulum laoreet urna diam, at sagittis risus pretium vitae. Donec eget feugiat mi. Morbi posuere nulla sem, a placerat arcu commodo ultrices. Nullam nec sollicitudin mi, quis laoreet sem. Vivamus egestas nisl purus, semper maximus turpis aliquet vel. Donec et molestie quam. Quisque ac nibh sed risus pretium posuere. Ut id vehicula libero. Mauris posuere nulla eget lorem condimentum euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque non pellentesque urna. Praesent consectetur lectus in sapien molestie, sit amet varius risus tincidunt.
      h4 Logline
      p Vestibulum at aliquet risus.
    div role="tabpanel" class="tab-pane" id="blog"
      h3
        | Nearing the Half-Way Mark!
        small
          |  April 24, 2015
      p
        | Updated by
        a
          |  Oompa-Loompa
      p Nulla facilisi. Phasellus pharetra et neque id placerat. Aenean ultrices dui augue, a luctus velit efficitur in. Curabitur vulputate, odio vel convallis feugiat, mi quam elementum nibh, eu porttitor dolor leo a quam. Cras ornare sem sapien. Donec velit diam, convallis quis eleifend ultrices, consectetur non enim. Sed pharetra ac nisl sed porta. Phasellus lorem nunc, bibendum sed fringilla vitae, convallis eu sapien. Duis semper sapien elit, et egestas velit fermentum ut. Sed in dictum odio. Etiam consectetur, quam vel sagittis sollicitudin, justo lectus lobortis arcu, at interdum ante metus aliquet est. Pellentesque elementum, turpis vitae laoreet vulputate, massa eros molestie quam, fermentum dignissim tortor risus eget nisi. Vestibulum ut hendrerit dolor, id porta mauris. Proin condimentum tortor in consequat dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse eleifend risus id viverra vulputate.
      p Etiam id scelerisque nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In feugiat, nisl a viverra egestas, lorem ipsum eleifend tellus, a pellentesque nulla tellus sed tortor. Sed condimentum at sapien a gravida. Fusce at faucibus metus. Vivamus a orci massa. Proin ultricies lectus quis ante porta, vel aliquam elit semper. Vivamus sed condimentum augue, ut scelerisque tellus. Phasellus dictum ex id ligula tempus venenatis. Nam et purus in nunc venenatis hendrerit a eu leo. Quisque aliquet lectus consectetur, consequat quam ac, eleifend lectus. Maecenas in blandit diam, nec tempus metus. Nullam pretium est vel quam dictum, a gravida neque pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum id neque congue, commodo ante vitae, consectetur augue. Nullam et cursus orci, non tempus purus.
      hr
      h3
        | First Hour Success!
        small
          |  April 24, 2015
      p
        | Updated by
        a
          |  ZeegoDoo
      p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vehicula at augue congue efficitur. Integer quis ultricies orci. Nullam vulputate efficitur dui. Proin tincidunt orci ut augue mollis, dictum tincidunt eros sagittis. Quisque condimentum dui lorem. Vestibulum id neque urna. Donec varius gravida nisi vel porttitor.
      p Sed nisl dui, bibendum non rhoncus a, consequat id ligula. Etiam tempus tellus ut velit feugiat tempus. Sed ultricies tellus eget elementum pretium. In quis varius lorem. Pellentesque laoreet sit amet metus id rutrum. Duis vel vehicula leo. Nullam volutpat sapien eget venenatis porttitor. Curabitur eget egestas diam. Maecenas fringilla neque id eros sodales, sed blandit quam faucibus.
      hr
      h3
        | Launch Day!
        small
          |  April 24, 2015
      p
        | Updated by
        a
          |  Muahaha
      p Morbi posuere nulla sem, a placerat arcu commodo ultrices. Nullam nec sollicitudin mi, quis laoreet sem. Vivamus egestas nisl purus, semper maximus turpis aliquet vel. Donec et molestie quam. Quisque ac nibh sed risus pretium posuere. Ut id vehicula libero. Mauris posuere nulla eget lorem condimentum euismod.
      p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque non pellentesque urna. Praesent consectetur lectus in sapien molestie, sit amet varius risus tincidunt. Vestibulum at aliquet risus.

    div role="tabpanel" class="tab-pane" id="team"
      h3 Team
      h4 About this team
      p Integer non massa mattis, feugiat turpis eu, tempor dui. Donec cursus leo turpis, vitae tempus dui efficitur eget. Pellentesque molestie orci ac tortor blandit blandit. Fusce ut faucibus nunc. Nulla a leo turpis. Vestibulum nec ex consequat, interdum arcu hendrerit, elementum sem.
      hr
      h4
        | Muahaha
        small  Director
      img class="pull-left" style="margin-right:18px" src="http://placekitten.com.s3.amazonaws.com/homepage-samples/96/139.jpg"
      p Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer arcu velit, tincidunt accumsan rutrum ac, dapibus eu orci. Phasellus dapibus erat quis faucibus pretium. Sed ornare auctor augue ac tincidunt. Integer non massa mattis, feugiat turpis eu, tempor dui. Donec cursus leo turpis, vitae tempus dui efficitur eget. Pellentesque molestie orci ac tortor blandit blandit. Fusce ut faucibus nunc. Nulla a leo turpis. Vestibulum nec ex consequat, interdum arcu hendrerit, elementum sem. Nullam velit dolor, porttitor id nisi non, sollicitudin mattis neque. In luctus ligula tellus, at vulputate ante maximus et. Phasellus condimentum arcu a enim vestibulum porttitor. Nam in tempor tellus. Sed non maximus nunc, et pretium dui.
      br
      h4
        | Oompa-Loompa
        small  Producer
      img class="pull-left" style="margin-right:18px" src="http://placekitten.com.s3.amazonaws.com/homepage-samples/96/139.jpg"
      p Proin nulla ante, commodo ac odio ac, consectetur maximus dolor. Mauris consequat mi sed elit tempus aliquam. Suspendisse malesuada risus ac dolor luctus, a vulputate tortor convallis. Duis ac pulvinar risus. Mauris semper dolor ut nisl dapibus, vel euismod metus porttitor. Duis malesuada mauris lacus, sed sollicitudin mauris mollis et. Ut ex nulla, eleifend ac tempor ac, venenatis vitae odio. Phasellus nec quam vel lorem mollis gravida. Proin ex diam, dictum id dignissim in, tempus non elit. Aliquam fermentum, diam a aliquam finibus, nibh libero euismod lacus, et porta dolor libero a lorem. Cras nec nibh est. Aenean eget lacinia mi, vitae finibus libero.
      br
      h4
        | ZeegoDoo
        small  Marketing
      img class="pull-left" style="margin-right:18px" src="http://placekitten.com.s3.amazonaws.com/homepage-samples/96/139.jpg"
      p Curabitur suscipit sapien eu elit ornare, eu consectetur mi scelerisque. Praesent interdum scelerisque sem in fermentum. Mauris feugiat eget risus ac commodo. Morbi gravida volutpat nisl, in luctus nunc interdum a. Phasellus nisl purus, ultricies ac neque eu, bibendum dapibus eros. Nam sagittis aliquet porttitor. In massa ex, dictum sit amet gravida sit amet, dapibus et dolor. Pellentesque eget ante vel nunc sodales vestibulum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus at nunc dignissim, suscipit neque nec, tempor felis. Curabitur vel suscipit arcu. Aliquam fringilla ipsum magna, aliquet consequat quam hendrerit id. Praesent nec orci sed ipsum finibus tempor.
      br
    div role="tabpanel" class="tab-pane" id="backers"
      h3 Backers
      ul#backers
        li
          img.pull-left src=@avatar
          span.h4  Oompa-Loompa
          p  Helped with a cash funding of $13, April 24, 2015
        li
          img.pull-left src=@avatar
          span.h4  Echego
          p  Helped with a cash funding of $87,383, April 24, 2015
        li
          img.pull-left src=@avatar
          span.h4  Reginald
          p  Helped fund 17 canaries, April 24, 2015
        li
          img.pull-left src=@avatar
          span.h4  Rasha
          p  Helped fund 1 blue tiger and with a cash funding of $1, April 24, 2015
        li
          img.pull-left src=@avatar
          span.h4  Gary Oldman
          p  Helped with a cash funding of $134, April 24, 2015
        li
          img.pull-left src=@avatar
          span.h4  Harry Potter
          p  Helped fund 1 magical wand, April 24, 2015

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "KickDoc"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'



  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-header href=root_path
            = image_tag("Kickdoc.png", alt: "KickDoc", height: "110", margin: "0")

          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav.navbar-right
              li= link_to "Choose", documentaries_path
              li= link_to "Fund", documentaries_path(:status => :fund)
              li= link_to "Launch", new_documentary_path
              li= link_to "Watch", "/path3"
              li= link_to "How it works", "welcome/how_it_works"
              li
                form.navbar-form.navbar-left role="search"
                  .form-group
                    input type="text" class="form-control" placeholder="Search"
                  button type="submit" class="btn btn-default"
                    | Submit
              - if current_user.is_authenticated?
                li.dropdown
                  a.dropdown-toggle data-toggle="dropdown" role="button" aria-expanded="false"
                    i.fa.fa-child
                    |  Gerardo Cepeda
                    .span class="caret"
                  ul.dropdown-menu role="menu"
                    li
                      = link_to '#', class: "a.btn btn-block btn-social"
                        i.fa.fa-user
                        |  My Profile
                    li
                      = link_to sessions_path(), method: :delete, class: "a.btn btn-block btn-social"
                        i.fa.fa-sign-out
                        |  Logout
              - else
                li
                  = link_to new_sessions_path(), class: "a.btn btn-block btn-social btn-twitter"
                      i.fa.fa-sign-in
                      |  Sign in

    .container
      .row
        div class="#{current_page?(documentaries_url) && !all_genres.blank? ? "col-lg-9" : "col-lg-12"}"
          = bootstrap_flash
          = yield

        = yield(:right_panel)

      footer
        p &copy; NFB/ONF 2015

    = javascript_include_tag "application"

app/views/welcome/how_it_works.html.slim
h1
  | KickDoc
  small How it works?

.embed-responsive.embed-responsive-16by9
  iframe.embed-responsive-item src="https://player.vimeo.com/video/125937937" width="516"
br
p
  | Because our source of inspiration has always been our people, <b>KickDoc</b> will offer new way to get involved in what
  |  National Film Board of Canada produces. Canayan citizens now have the power to choose what they want to show
  |  about their reality and culture to the World.
  | This is possible by changing the way we fund documentary productions. Our model consist of two main phases:
.panel.panel-primary
  .panel-heading
    h2.panel-title.panel-primary
    |   First phase canayan citizens vote
  .panel-body
    | The most popular projects get founded 100% by NFB
.panel.panel-primary
  .panel-heading
    h2.panel-title.panel-primary
    |   Second phase canayan citizens fund
  .panel-body
    | The other popular projects who will not be 100% funded by NFB will be partially
    |  fund by NFB. The canayan citizen will be able to contribute finantially during a time span
    |  of 30-60 days to make the project happen. <b>KickDoc</b> gives the voice and the choice to canayans to show
    |  the true face of Canada to the world. This project aims to reinforce NFB's mission to <quote><i>"Reflect Canada to
    |  Canadians and the world.”</i></quote>

h1
  | Architecture
.panel.panel-default
  .panel-body
    =image_tag("kickdocs_2.jpg")

app/views/welcome/index.html.slim
- if @my_documentaries.blank?
  .lead
    p
      | KickDoc is a new way to get involved in what National Film Board of Canada produce.
    p
      | Because our source of inspiration has always been our people, canadian citizen have the power to choose what they will love to watch.
- else
  h1
    | Welcome to KickDoc

  h3
    | My Timeline

  - @my_documentaries.each_with_index do |documentary, index|
    .panel.panel-default
      .panel-heading
        .pull-right
          = (DateTime.now - index).strftime("%B %d, %Y")
        h1
          = documentary.title
      .panel-body
        .row
          .col-xs-2
            .thumbnail
              = link_to(image_tag(documentary.thumbnail_url, :size => "121x110"), documentary_path(documentary.id))
          .col-xs-8
            | Continue to vote for him !!!!!
      .panel-footer
        .row
          .col-xs-4
            .i.fa.fa-user
              = documentary.creator
          .col-xs-6
            .i.fa.fa-heart
              = "%s" % documentary.backers
          .col-xs-2
            .i.fa.fa-clock-o
              = documentary.expired_at.strftime("%B %d, %Y")
        .row
          .col-xs-12
            .progress
              .progress-bar role="progressbar" aria-valuenow=documentary.percent_funded aria-valuemin="0" aria-valuemax="100" style="width: #{documentary.percent_funded}%;"
                = "%s %" % documentary.percent_funded